id: extra_health
trigger:
  origin: { x: 167, y: 1, z: 7 }
  lengths: { x: 1, y: 1, z: 1 }
predicateEvaluation: ALL_TRUE
data:
  predicates:
    - type: zombies.map.shop.predicate.player_state
      states: [ zombies.player.state.alive ]
      blacklist: false

    - type: zombies.map.shop.predicate.in_game

    - type: zombies.map.shop.predicate.type
      types: [ zombies.map.shop.interaction.right_click_block ]
      blacklist: false

  successInteractors:
    - type: zombies.map.shop.interactor.conditional
      evaluation: ALL_TRUE
      predicates:
        - type: zombies.map.shop.predicate.map_flag
          flag: zombies.map.flag.power
          requireAbsent: false
      successInteractors:
        - type: zombies.map.shop.interactor.conditional
          evaluation: ALL_TRUE
          predicates:
            - type: zombies.map.shop.predicate.static_cost
              cost: 3000
              modifierType: coin_spend.shop
          successInteractors:
            - type: zombies.map.shop.interactor.add_equipment
              equipmentKey: extra_health
              groupKey: zombies.group.perk
              allowReplace: true
              allowDuplicate: false
              specificSlot: -1
              successInteractors:
                - type: zombies.map.shop.interactor.play_sound
                  sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                           volume: 10.0,
                           pitch: 1.0 }
                  broadcast: false

                - type: zombies.map.shop.interactor.deduct_coins
                  cost: 3000
                  modifierType: coin_spend.shop

                - type: zombies.map.shop.interactor.messaging
                  messages: [ "<yellow>You activated <blue>Extra Health</blue>!</yellow>" ]
                  broadcast: false
              failureInteractors:
                - type: zombies.map.shop.interactor.conditional
                  evaluation: ALL_TRUE
                  predicates:
                    - type: zombies.map.shop.equipment_predicate.present
                      equipmentGroup: zombies.group.perk
                      equipmentKey: extra_health
                      requirePresent: true
                      requireHeld: false
                  successInteractors:
                    - type: zombies.map.shop.interactor.messaging
                      messages: [ "<red>You have already activated Extra Health!" ]
                      broadcast: false
                  failureInteractors:
                    - type: zombies.map.shop.interactor.messaging
                      messages: [ "<red>Hold a perk and <key:key.use> again to replace it!" ]
                      broadcast: false

                - type: zombies.map.shop.interactor.play_sound
                  sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                           pitch: 0.0 }
                  broadcast: false

          failureInteractors:
            - type: zombies.map.shop.interactor.messaging
              messages: [ "<red>You do not have enough coins to purchase this!" ]
              broadcast: false

            - type: zombies.map.shop.interactor.play_sound
              sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                       pitch: 0.0 }
              broadcast: false

      failureInteractors:
        - type: zombies.map.shop.interactor.messaging
          messages: [ "<red>Perk Machines require power to use! Find and activate the</red> <dark_purple>Power Switch</dark_purple> <red>in</red> <green><b>Generator</b></green> <red>first!</red>" ]
          broadcast: false

        - type: zombies.map.shop.interactor.play_sound
          sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                   pitch: 0.0 }
          broadcast: false

  failureInteractors: [ ]
  displays:
    - type: zombies.map.shop.display.flag_conditional
      flag: zombies.map.flag.power
      success:
        - type: zombies.map.shop.display.player
          displayCreator:
            type: zombies.map.shop.display.player.conditional
            predicate:
              type: zombies.player.condition.has_equipment
              groupKey: zombies.group.perk
              equipmentKey: extra_health
            success:
              - type: zombies.map.shop.display.player.hologram
                info:
                  text: [ "<blue><b>Extra Health", "<green>ACTIVE" ]
                  position:
                    x: -0.5
                    y: 0.25
                    z: -0.25
            failure:
              - type: zombies.map.shop.display.player.hologram
                info:
                  text: [ "<blue><b>Extra Health", "<gold>3000 Coins" ]
                  position:
                    x: -0.5
                    y: 0.25
                    z: -0.25

      failure:
        - type: zombies.map.shop.display.static_hologram
          info:
            text: [ "<blue><b>Extra Health", "<grey><i>Requires power!" ]
            position:
              x: -0.5
              y: 0.25
              z: -0.25
