listFormat = "<gradient:#616575:#4a4c59><st>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯</st></gradient><br><#fffa9e>»</#fffa9e> <b><yellow>Modifier Key:</yellow></b> <#9096ad><modifier_key></#9096ad><br>  <yellow>Active Modifiers:</yellow> <#9096ad><modifiers></#9096ad><br><gradient:#616575:#4a4c59><st>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯</st></gradient>"
clearFormat = "<green>Removed <yellow><modifier_count></yellow> modifiers</green>"
showConflictsFormat = "<red>Conflicting modifiers:</red> <#9096ad><conflicts>"
internalError = "<red>An internal error occurred when executing this command, please report this incident to server staff!"
invalidModifier = "<red>Invalid modifier name!"
modifierEnabled = "<green>Enabled modifier!"
modifierDisabled = "<green>Disabled modifier!"
modifierAlreadyEnabled = "<red>Modifier is already enabled!"
noEnabledModifiers = "<red>There are no enabled modifiers!"
enabledModifiers = "<green>Enabled modifiers!"
modifierKeyTooLong = "<red>That modifier key is too long!"
noPermission = "<red>You do not have permission to use this modifier!"
modifierDoesNotExistFormat = "<red><modifier> does not exist!</red>"

