id: ammo_refill
trigger:
  origin: { x: 30, y: 0, z: -14 }
  lengths: { x: 1, y: 1, z: 1 }
predicateEvaluation: ALL_TRUE
data:
  predicates:
    - type: zombies.map.shop.predicate.player_state
      states: [ zombies.player.state.alive ]
      blacklist: false

    - type: zombies.map.shop.predicate.in_game

    - type: zombies.map.shop.predicate.type
      types: [ zombies.map.shop.interaction.right_click_block ]
      blacklist: false

  successInteractors:
    - type: zombies.map.shop.interactor.conditional
      evaluation: ALL_TRUE
      predicates:
        - type: zombies.map.shop.predicate.map_flag
          flag: zombies.map.flag.power
          requireAbsent: false
      successInteractors:
        - type: zombies.map.shop.interactor.conditional
          evaluation: ALL_TRUE
          predicates:
            - type: zombies.map.shop.predicate.static_cost
              cost: 600
              modifierType: coin_spend.shop
          successInteractors:
            - type: zombies.map.shop.interactor.conditional
              evaluation: ALL_TRUE
              predicates:
                - type: zombies.map.shop.predicate.not
                  predicate:
                    type: zombies.map.shop.predicate.gun_full
                    equipmentKey: ignored
                    onlyHeld: false
                    matchKey: false
              successInteractors:
                - type: zombies.map.shop.interactor.refill_ammo
                  equipmentKey: ignored
                  onlyHeld: false
                  matchKey: false

                - type: zombies.map.shop.interactor.play_sound
                  sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                           volume: 10.0,
                           pitch: 1.0 }
                  broadcast: false

                - type: zombies.map.shop.interactor.deduct_coins
                  cost: 600
                  modifierType: coin_spend.shop

                - type: zombies.map.shop.interactor.messaging
                  messages: [ "<green>You refilled all of your ammo!" ]
                  broadcast: false
              failureInteractors:
                - type: zombies.map.shop.interactor.messaging
                  messages: [ "<red>All your guns are already filled!" ]
                  broadcast: false

                - type: zombies.map.shop.interactor.play_sound
                  sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                           pitch: 0.0 }
                  broadcast: false

          failureInteractors:
            - type: zombies.map.shop.interactor.messaging
              messages: [ "<red>You do not have enough coins to purchase this!" ]
              broadcast: false

            - type: zombies.map.shop.interactor.play_sound
              sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                       pitch: 0.0 }
              broadcast: false

      failureInteractors:
        - type: zombies.map.shop.interactor.messaging
          messages: [ "<red>Perk Machines require power to use! Find and activate the</red> <dark_purple>Power Switch</dark_purple> <red>in the</red> <green><b>Garage</b></green> <red>first!</red>" ]
          broadcast: false

        - type: zombies.map.shop.interactor.play_sound
          sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                   pitch: 0.0 }
          broadcast: false

  failureInteractors: [ ]
  displays:
    - type: zombies.map.shop.display.flag_conditional
      flag: zombies.map.flag.power
      success:
        - type: zombies.map.shop.display.static_hologram
          info:
            text: [ "<blue><b>Ammo Refill", "<gold>600 Coins" ]
            position:
              x: 0.5
              y: 1.0
              z: -0.25

      failure:
        - type: zombies.map.shop.display.static_hologram
          info:
            text: [ "<blue><b>Ammo Refill", "<grey><i>Requires power!" ]
            position:
              x: 0.5
              y: 1.0
              z: -0.25
