id: gold_upper
trigger:
  origin: { x: 7, y: 0, z: -31 }
  lengths: { x: 1, y: 3, z: 3 }
predicateEvaluation: ALL_TRUE
data:
  predicates:
    - type: zombies.map.shop.predicate.player_state
      states: [ zombies.player.state.alive ]
      blacklist: false

    - type: zombies.map.shop.predicate.in_game

    - type: zombies.map.shop.predicate.type
      types: [ zombies.map.shop.interaction.right_click_entity ]
      blacklist: false

  successInteractors:
    - type: zombies.map.shop.interactor.conditional
      evaluation: ALL_TRUE
      predicates:
        - type: zombies.map.shop.predicate.static_cost
          cost: 400
          modifierType: coin_spend.shop
      successInteractors:
        - type: zombies.map.shop.interactor.add_equipment
          groupKey: zombies.group.armor
          equipmentKey: golden_helmet
          allowReplace: false
          allowDuplicate: false
          specificSlot: 41
          successInteractors:
            - type: zombies.map.shop.interactor.messaging
              messages: [ "<green>You purchased <blue>Golden Chestplate</blue>!</green>" ]
              broadcast: false

            - type: zombies.map.shop.interactor.deduct_coins
              cost: 400
              modifierType: coin_spend.shop

            - type: zombies.map.shop.interactor.play_sound
              sound: { name: 'minecraft:block.note_block.pling', source: PLAYER, volume:
                10.0,  pitch: 2.0 }
              broadcast: false
          failureInteractors:
            - type: zombies.map.shop.interactor.messaging
              messages: [ "<red>You have already purchased Golden Chestplate!" ]
              broadcast: false

            - type: zombies.map.shop.interactor.play_sound
              sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                       pitch: 0.0 }
              broadcast: false
        - type: zombies.map.shop.interactor.add_equipment
          groupKey: zombies.group.armor
          equipmentKey: golden_chestplate
          allowReplace: false
          allowDuplicate: false
          specificSlot: 42
          successInteractors: [ ]
          failureInteractors: [ ]
      failureInteractors:
        - type: zombies.map.shop.interactor.messaging
          messages: [ "<red>You don't have enough coins to purchase Golden Chestplate!" ]
          broadcast: false

        - type: zombies.map.shop.interactor.play_sound
          sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                   pitch: 0.0 }
          broadcast: false

  failureInteractors: [ ]
  displays:
    - type: zombies.map.shop.display.interaction_point
      offset:
        x: 0
        y: 0
        z: 0

    - type: zombies.map.shop.display.player
      displayCreator:
        type: zombies.map.shop.display.player.conditional
        predicate:
          type: zombies.player.condition.has_equipment
          groupKey: zombies.group.armor
          equipmentKey: golden_helmet
        success:
          - type: zombies.map.shop.display.player.hologram
            info:
              text: [ "<green>Golden Chestplate", "<gold>UNLOCKED" ]
              position:
                x: 0
                y: -1.5
                z: 0
        failure:
          - type: zombies.map.shop.display.player.hologram
            info:
              text: [ "<green>Golden Chestplate", "<gold>400 Coins" ]
              position:
                x: 0
                y: -1.5
                z: 0

    - type: zombies.map.shop.display.player
      displayCreator:
        type: zombies.map.shop.display.player.combining_armor
        face: WEST
        small: true
        offset: { x: 0, y: -0.5, z: 0 }
        items:
          - key: HELMET
            value:
              stack: '{id:"minecraft:golden_helmet",Count:1}'
              tier: 0

          - key: CHESTPLATE
            value:
              stack: '{id:"minecraft:golden_chestplate",Count:1}'
              tier: 0
