type: npc.entity
location: { x: -38, y: 21.75, z: 147.5, yaw: -180.0, pitch: 0.0 }
entity:
  type: npc.entity.supplier.mob
  entityType: 'minecraft:armor_stand'
settings:
  type: npc.entity.settings
  invisible: true
  small: true
  displayName: <red>Rejoin
ticker:
  type: npc.entity.ticker.none
interactor:
  type: npc.interactor.none