id: phantazm:powerup_shop
trigger:
  origin: {x: 58, y: 10, z: -5}
  lengths: {x: 1, y: 1, z: 1}
predicateEvaluation: ALL_TRUE
data:
  predicates:
    - type: zombies.map.shop.predicate.player_state
      states: [ zombies.player.state.alive ]
      blacklist: false

    - type: zombies.map.shop.predicate.in_game

    - type: zombies.map.shop.predicate.type
      types: [ zombies.map.shop.interaction.right_click_block ]
      blacklist: false
  successInteractors:
    - type: zombies.map.shop.interactor.conditional
      evaluation: ALL_TRUE
      predicates:
        - type: zombies.map.shop.predicate.map_flag
          flag: zombies.map.flag.power
          requireAbsent: false
      successInteractors:
        - type: zombies.map.shop.interactor.open_gui
          title: "Powerup Shop"
          inventoryType: CHEST_3_ROW
          dynamic: false
          guiItems:
            - type: zombies.map.shop.gui.click_handler.interacting
              clickTypes: [ LEFT_CLICK ]
              blacklist: false
              updatingItem:
                type: item.updating.static
                item:
                  material: 'minecraft:arrow'
                  displayName: "<!i><blue><b>Max Ammo</b></blue>"
                  lore:
                    - '<!i><#9096ad>Finally, cheap ammo refills in Fallen Grounds.</#9096ad></!i>'
                    - '<!i><#9096ad>This doesn''t feel like the same game.</#9096ad></!i>'
                    - ''
                    - '<!i><#9096ad><b>Cost<#b8bfde>:</#b8bfde> <gold>1000 Coins</gold></b></#9096ad></!i>'

              clickInteractor:
                type: zombies.map.shop.interactor.conditional
                evaluation: ALL_TRUE
                predicates:
                  - type: zombies.map.shop.predicate.static_cost
                    cost: 1000
                    modifierType: coin_spend.shop
                successInteractors:
                  - type: zombies.map.shop.interactor.spawn_powerup
                    coordinate: { x: 58, y: 9, z: -6 }
                    powerup: 'phantazm:max_ammo'

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                             volume: 10.0,
                             pitch: 1.0 }
                    broadcast: true

                  - type: zombies.map.shop.interactor.deduct_coins
                    cost: 1000
                    modifierType: coin_spend.shop

                  - type: zombies.map.shop.interactor.messaging
                    messages: [ '<#9096ad><sender> bought <blue><b>Max Ammo</b></blue> from the <yellow>Powerup Shop</yellow>!<#9096ad>' ]
                    broadcast: true
                failureInteractors:
                  - type: zombies.map.shop.interactor.messaging
                    messages: [ "<red>You do not have enough coins to purchase this!" ]
                    broadcast: false

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                             pitch: 0.0 }
                    broadcast: false

            - type: zombies.map.shop.gui.click_handler.interacting
              clickTypes: [ LEFT_CLICK ]
              blacklist: false
              updatingItem:
                type: item.updating.static
                item:
                  material: 'minecraft:raw_gold'
                  displayName: "<!i><gold><b>Double Coins</b></gold>"
                  lore:
                    - '<!i><#9096ad>Sacrifice your money so your teammates</#9096ad></!i>'
                    - '<!i><#9096ad>get a boost. Is this philanthropy?</#9096ad></!i>'
                    - ''
                    - '<!i><#9096ad><b>Cost<#b8bfde>:</#b8bfde> <gold>2500 Coins</gold></b></#9096ad></!i>'

              clickInteractor:
                type: zombies.map.shop.interactor.conditional
                evaluation: ALL_TRUE
                predicates:
                  - type: zombies.map.shop.predicate.static_cost
                    cost: 2500
                    modifierType: coin_spend.shop
                successInteractors:
                  - type: zombies.map.shop.interactor.spawn_powerup
                    coordinate: { x: 58, y: 9, z: -6 }
                    powerup: 'phantazm:double_coins'

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                             volume: 10.0,
                             pitch: 1.0 }
                    broadcast: true

                  - type: zombies.map.shop.interactor.deduct_coins
                    cost: 2500
                    modifierType: coin_spend.shop

                  - type: zombies.map.shop.interactor.messaging
                    messages: [ '<#9096ad><sender> bought <gold><b>Double Coins</b></gold> from the <yellow>Powerup Shop</yellow>!<#9096ad>' ]
                    broadcast: true
                failureInteractors:
                  - type: zombies.map.shop.interactor.messaging
                    messages: [ "<red>You do not have enough coins to purchase this!" ]
                    broadcast: false

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                             pitch: 0.0 }
                    broadcast: false
            - type: zombies.map.shop.gui.click_handler.interacting
              clickTypes: [ LEFT_CLICK ]
              blacklist: false
              updatingItem:
                type: item.updating.static
                item:
                  material: 'minecraft:clock'
                  displayName: "<!i><aqua><b>Overclock</b></aqua>"
                  lore:
                    - '<!i><#9096ad>You came here to kick butt and</#9096ad></!i>'
                    - '<!i><#9096ad>chew bubblegum, but you''re down</#9096ad></!i>'
                    - '<!i><#9096ad>some coins for it.</#9096ad></!i>'
                    - ''
                    - '<!i><#9096ad><b>Cost<#b8bfde>:</#b8bfde> <gold>5000 Coins</gold></b></#9096ad></!i>'

              clickInteractor:
                type: zombies.map.shop.interactor.conditional
                evaluation: ALL_TRUE
                predicates:
                  - type: zombies.map.shop.predicate.static_cost
                    cost: 5000
                    modifierType: coin_spend.shop
                successInteractors:
                  - type: zombies.map.shop.interactor.spawn_powerup
                    coordinate: { x: 58, y: 9, z: -6 }
                    powerup: 'phantazm:overclock'

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                             volume: 10.0,
                             pitch: 1.0 }
                    broadcast: true

                  - type: zombies.map.shop.interactor.deduct_coins
                    cost: 5000
                    modifierType: coin_spend.shop

                  - type: zombies.map.shop.interactor.messaging
                    messages: [ '<#9096ad><sender> bought <aqua><b>Overclock</b></aqua> from the <yellow>Powerup Shop</yellow>!<#9096ad>' ]
                    broadcast: true
                failureInteractors:
                  - type: zombies.map.shop.interactor.messaging
                    messages: [ "<red>You do not have enough coins to purchase this!" ]
                    broadcast: false

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                             pitch: 0.0 }
                    broadcast: false
            - type: zombies.map.shop.gui.click_handler.interacting
              clickTypes: [ LEFT_CLICK ]
              blacklist: false
              updatingItem:
                type: item.updating.static
                item:
                  material: 'minecraft:bedrock'
                  displayName: "<!i><dark_gray><b>Invincibility</b></dark_gray>"
                  lore:
                    - '<!i><#9096ad>Unstoppable zombie meets immovable</#9096ad></!i>'
                    - '<!i><#9096ad>survivor.</#9096ad></!i>'
                    - ''
                    - '<!i><#9096ad><b>Cost<#b8bfde>:</#b8bfde> <gold>7500 Coins</gold></b></#9096ad></!i>'

              clickInteractor:
                type: zombies.map.shop.interactor.conditional
                evaluation: ALL_TRUE
                predicates:
                  - type: zombies.map.shop.predicate.static_cost
                    cost: 7500
                    modifierType: coin_spend.shop
                successInteractors:
                  - type: zombies.map.shop.interactor.spawn_powerup
                    coordinate: { x: 58, y: 9, z: -6 }
                    powerup: 'phantazm:invincibility'

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                             volume: 10.0,
                             pitch: 1.0 }
                    broadcast: true

                  - type: zombies.map.shop.interactor.deduct_coins
                    cost: 7500
                    modifierType: coin_spend.shop

                  - type: zombies.map.shop.interactor.messaging
                    messages: [ '<#9096ad><sender> bought <dark_gray><b>Invincibility</b></dark_gray> from the <yellow>Powerup Shop</yellow>!<#9096ad>' ]
                    broadcast: true
                failureInteractors:
                  - type: zombies.map.shop.interactor.messaging
                    messages: [ "<red>You do not have enough coins to purchase this!" ]
                    broadcast: false

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                             pitch: 0.0 }
                    broadcast: false
            - type: zombies.map.shop.gui.click_handler.interacting
              clickTypes: [ LEFT_CLICK ]
              blacklist: false
              updatingItem:
                type: item.updating.cost_substituting
                material: 'minecraft:player_head'
                displayName: "<!i><#e61927><b>Insta Kill</b></#e61927>"
                tag: '{SkullOwner:{Id:[I;-967193132,-466204297,-1498950319,-1900097605],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWFlMzg1NWY5NTJjZDRhMDNjMTQ4YTk0NmUzZjgxMmE1OTU1YWQzNWNiY2I1MjYyN2VhNGFjZDQ3ZDMwODEifX19"}]}}}'
                lore:
                  - '<!i><#9096ad>Kill them. Kill them all.</#9096ad></!i>'
                  - ''
                  - '<!i><#9096ad><b>Cost<#b8bfde>:</#b8bfde> <gold><cost> Coins</gold></b></#9096ad></!i>'
                cost: 5000
                modifier: coin_spend.shop.insta_kill

              clickInteractor:
                type: zombies.map.shop.interactor.conditional
                evaluation: ALL_TRUE
                predicates:
                  - type: zombies.map.shop.predicate.static_cost
                    cost: 5000
                    modifierType: coin_spend.shop.insta_kill
                successInteractors:
                  - type: zombies.map.shop.interactor.spawn_powerup
                    coordinate: { x: 58, y: 9, z: -6 }
                    powerup: 'phantazm:insta_kill'

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.firework_rocket.twinkle', source: PLAYER,
                             volume: 10.0,
                             pitch: 1.0 }
                    broadcast: true

                  - type: zombies.map.shop.interactor.deduct_coins
                    cost: 5000
                    modifierType: coin_spend.shop.insta_kill

                  - type: zombies.map.shop.interactor.messaging
                    messages: [ '<#9096ad><sender> bought <#e61927><b>Insta Kill</b></#e61927> from the <yellow>Powerup Shop</yellow>!<#9096ad>' ]
                    broadcast: true

                  - type: zombies.map.shop.interactor.cumulative_transaction_modifier
                    modifierGroup: coin_spend.shop.insta_kill
                    modifierAction: ABS_ADD
                    amount: 5000
                failureInteractors:
                  - type: zombies.map.shop.interactor.messaging
                    messages: [ "<red>You do not have enough coins to purchase this!" ]
                    broadcast: false

                  - type: zombies.map.shop.interactor.play_sound
                    sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                             pitch: 0.0 }
                    broadcast: false
      failureInteractors:
        - type: zombies.map.shop.interactor.messaging
          messages: [ <red>Powerup Shop requires power to use! Find and activate the</red>
            <dark_purple>Power Switch</dark_purple> <red>in the</red> <green><b>Garage</b></green>
            <red>first!</red> ]
          broadcast: false

        - type: zombies.map.shop.interactor.play_sound
          sound: { name: 'minecraft:entity.enderman.teleport', source: PLAYER, volume: 10.0,
                   pitch: 0.0 }
          broadcast: false
  failureInteractors: []
  displays:
  - type: zombies.map.shop.display.flag_conditional
    flag: zombies.map.flag.power
    success:
      - type: zombies.map.shop.display.static_hologram
        info:
          text: [ "<dark_purple><b>Powerup Shop", "<yellow>RIGHT-CLICK TO OPEN" ]
          position:
            x: 1.0
            y: 1.0
            z: 0.2
    failure:
      - type: zombies.map.shop.display.static_hologram
        info:
          text: [ "<dark_purple><b>Powerup Shop", "<grey><i>Requires power!" ]
          position:
            x: 1.0
            y: 1.0
            z: 0.2
